name: "APIsec|SCAN - Dynamic API Security Testing"
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  test_scan:
    permissions:
      contents: read # to checkout repository code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O validBaseurlNetbanking.json https://raw.githubusercontent.com/ImranShaik065/ListAPIs/main/validBaseurlNetbanking.json
      - name: APISec|SCAN Testing
        uses: apisec-university/free-API-security-test-action@beta
        with:
          base_url: "http://netbanking.apisec.ai:8080"
          specification_path: "validBaseurlNetbanking.json"
          #apisecu_token: "U2FsdGVkX1+KKM/gO98RTvrMSX6te9r1+fisGSxR80U="
      - name: Check files and folders
        run: |          
          ls -la
          pwd
